[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.0"
hooks = [
  { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },
  { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "https://github.com/DetachHead/basedpyright-prek-mirror"
rev = "1.39.9"
hooks = [
    { id = "basedpyright"}
]
