[environment]
root = ["."]
python-version = "3.14"
python-platform = "all"

# [src]
# include = [
#   "main.py",
#   "app/**/*.py",
#   "scripts/**/*.py",
#   "build.spec",
#   "updater.spec",
# ]

[[overrides]]
include = ["app/utils/toast.py"]

[overrides.analysis]
allowed-unresolved-imports = [
  "windows_toasts",
  "winrt.windows.ui.notifications",
]
