name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            runner: ubuntu-22.04
          - os: windows
            runner: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Build config-gui with PyInstaller
        run: uv run pyinstaller config-gui.spec

      - name: Build wplace-auto-painter with PyInstaller
        run: uv run pyinstaller wplace-auto-painter.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.platform.os }}
          path: |
            dist/
